@startuml
autonumber

Actor User
activate User
User -> SPA : List floors with a minimum and a maximum number of floors
activate SPA

SPA --> User : Requests data (minFloors, maxFloors)
deactivate SPA

User -> SPA : Inserts requested data

activate SPA
SPA -> BuildingRepo : GET/Building/{buildingId, name, description, dimension, code}
activate BuildingRepo

BuildingRepo --> SPA : status code
deactivate BuildingRepo

alt successfull case
    SPA --> User : List returned successfully
else failure
    SPA --> User : List not returned
end


@enduml
