@startuml

skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US150

actor "User" as User
participant "SPA" as SPA
participant "Building" as Building

activate User

User -> SPA : Asks to create a building
activate SPA
SPA -> User: Requests building data (name, description, dimension, code)
User -> SPA: Inserts requested data

SPA -> Building: POST/ building{name, description, dimension, code}
activate Building
Building -> SPA: Status code
deactivate

alt successfull case
SPA -> User: Building is created successfully
else failure case
SPA -> User: Building is not created
end

@enduml
