@startuml
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US240

actor "User" as User
participant "UI" as UI

activate User
User -> UI : 1 : Initiates passage creation process
activate UI
UI --> User : 1.1 : Requests data (fromFloorId,toFloorId,description)
deactivate UI
User -> UI : 2 : Inserts the requested data
activate UI
UI --> User : 2.1 : Displays success confirmation and the information of the created passage

deactivate UI

@enduml
