@startuml

skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US150

actor "User" as User
participant "SPA" as SPA
participant "Floor" as Floor

activate User

User -> SPA : Asks to create a floor
activate SPA
SPA -> User: Requests floor data (floorNumber, buildingId, description)
User -> SPA: Inserts requested data

SPA -> Floor: POST/ floor{floorNumber, buildingId, description}
activate Floor
Floor -> SPA: Status code
deactivate

alt successfull case
SPA -> User: Floor is created successfully
else failure case
SPA -> User: Floor is not created
end

@enduml
