@startuml
Actor User
activate User

User -> UI : Asks to create a passage between buildings
activate UI
UI --> User : Requests data  (fromFloorId, toFloorId, description)
deactivate UI

User -> UI : Inserts requested data
activate UI
UI --> User : Displays operation's success
deactivate UI


@enduml
