@startuml
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: US170

actor "User" as User
participant "UI" as UI

activate User
activate UI
User -> UI : 1 : Requests list of all buildings
UI --> User : Returns JSON with requested list


@enduml
