@startuml domain

skinparam linetype ortho


'========================================================
rectangle #F4EDED{
class Task << Root >> << Entity >>
class TaskType << (v,#A4C2E5) ValueObject >>
class TaskDescription << (v,#A4C2E5) ValueObject >>
}
'========================================================
rectangle #F9DB6D{
class Route << Root >> << Entity >>
class Path << Entity >>
class Point << (v,#A4C2E5) ValueObject >>

}
'========================================================
rectangle #464D77{
class Robot << Root >> << Entity >>

class Drone  << Entity >>

class MobileRobot  << Entity >>

class Code  << (v,orange) ValueObject >> << unique >>

class AvailableTask  << (v,#A4C2E5) ValueObject >>

class Nickname  << (v,#A4C2E5) ValueObject >>

class OperationStatus  << (v,#A4C2E5) ValueObject >>

class SerialNumber  << (v,#A4C2E5) ValueObject >>

}
'========================================================
rectangle #36827F{
class Building  << Root >> << Entity >>
class BuildingDescription  << (v,#A4C2E5) ValueObject >>
class BuildingName  << (v,orange) ValueObject >> << unique >>


class Floor  << Entity >>
class FloorNumber  << (v,#A4C2E5) ValueObject >>
class FloorDescription  << (v,#A4C2E5) ValueObject >>

class FloorMap  << Entity >>

class Passageway  << Entity >>

class Elevator  << Entity >>

class Room << Entity >>
class RoomId << (v,orange) ValueObject >> << unique >>

}
'========================================================


Robot <|-u- MobileRobot
Robot <|-u- Drone
Robot "1"-l->"1" Code
Robot "*"-d->"1" AvailableTask
Robot "*"-d->"1" OperationStatus
Robot "*"-d->"1" Nickname
Robot "*"-d->"1" SerialNumber

Task "*"-l>"1" Route
Task "*"-->"1" TaskType
Task "*"-->"1" TaskDescription
Task -> Building

Route "*"-->"1.." Path
Path "1"-r-->"1.." Robot : "Made by"
Path "*"->"1" Point
Path "*"->"1" Point



Building "1"-u->"*" Floor
Building "1"-r->"0..1" Elevator
Building "*"-->"0..1" BuildingDescription
Building "1"-->"1" BuildingDescription

Room "1"-u->"1" RoomId


Floor "2"-l->"0..*" Passageway

Floor "1"-r->"1" FloorMap
Floor "1"-u->"*" Room
Floor "*"-u->"1" FloorNumber
Floor "*"-u->"1" FloorDescription
@enduml
